---
fullname: Modular Finite Maps over Ordered Types
shortname: coq-mmaps
organization: coq-community
opam_name: coq-mmaps
community: true
action: true

synopsis: Several implementations of finite maps over arbitrary ordered types using Coq functors

description: |-
  This project contains several implementations of finite maps,
  including implementations based on AVL trees and red-black trees.
  The finite maps are parameterized on arbitrary ordered types using
  Coq functors. This is an updated version of the Coq Stdlib's FMaps
  that is meant to complement the Stdlib's MSet library.

publications:
- pub_url: https://www.cs.princeton.edu/~appel/papers/redblack.pdf
  pub_title: Efficient Verified Red-Black Trees
- pub_url: https://hal.inria.fr/hal-00150913
  pub_title: Functors for Proofs and Programs
  pub_doi: 10.1007/978-3-540-24725-8_26

authors:
- name: Pierre Letouzey
  initial: true

maintainers:
- name: Pierre Letouzey
  nickname: letouzey
- name: Karl Palmskog
  nickname: palmskog

opam-file-maintainer: palmskog@gmail.com

opam-file-version: dev

license:
  fullname: GNU Lesser General Public License v2.1 only
  identifier: LGPL-2.1-only

supported_coq_versions:
  text: 8.14 and later
  opam: '{>= "8.14"}'

tested_coq_opam_versions:
- version: 'dev'
- version: '8.17'
- version: '8.16'
- version: '8.15'
- version: '8.14'

namespace: MMaps

keywords:
- name: finite maps
- name: red-black trees
- name: AVL trees
- name: ordered types

categories:
- name: Computer Science/Data Types and Data Structures

documentation: |-
  ## Documentation

  As a starting point, you may consider [MMaps.Interface](Interface.v)
  and [MMaps.demo](demo.v).

  **Caveat** : This is work-in-progress, and might still change
  in the future, including `MMaps.Interface`.

  This is open source: patches, questions, comments are most welcome!
---
